export interface NodeData {
  id: string;
  code: string;
  name: string;
  initials: string;
  designation: string;
  department: string;
  standardVar: string;
  category: 'Core Engine' | 'Data Ingestion' | 'Governance' | 'Intelligence' | 'Compliance' | 'Settlement';
  angle: number;
  radius: number;
  height: number;
  description: string;
  formula: string;
  color: string;
  salaryNet: string;
  salaryGross: string;
  attendanceRate: string;
  statusPill: string;
  isEmployee: boolean;
  hash?: string;
  throughput?: string;
}

export const PAYPULSE_NODES: NodeData[] = [
  {
    id: 'mod-naming',
    code: 'SYS-NAM',
    name: 'Naming Conventions Engine',
    initials: 'NAM',
    designation: 'Deterministic Schema Mapper',
    department: 'Standardization',
    standardVar: 'schemaStandardizer',
    category: 'Core Engine',
    angle: 0,
    radius: 4.6,
    height: 0.6,
    description: 'Converts legacy and ambiguous column names into unambiguous, enterprise-standard camelCase mathematical schemas.',
    formula: 'map(legacyField) => standardSchemaField',
    color: '#00f0ff',
    salaryNet: '100% Deterministic',
    salaryGross: 'Zero Drift',
    attendanceRate: 'Realtime Translation',
    statusPill: 'Active 🟢',
    isEmployee: false,
    hash: '0x7F2A...9C1D',
    throughput: '42,000 mappings/s',
  },
  {
    id: 'mod-kernel',
    code: 'SYS-CALC',
    name: 'Mathematical Calculation Kernel',
    initials: 'CAL',
    designation: 'Gross-to-Net Compensation Core',
    department: 'Payroll Engine',
    standardVar: 'payrollKernel',
    category: 'Core Engine',
    angle: (Math.PI * 2 * 1) / 8,
    radius: 4.9,
    height: -0.3,
    description: 'Computes base compensation, statutory allowances, performance incentives, and tax deductions with zero floating-point drift.',
    formula: 'netPay = (baseMonthly + stdAllowances + adHocBonus) - deductions',
    color: '#10b981',
    salaryNet: 'Cent Precision',
    salaryGross: '0.00% Variance',
    attendanceRate: '10,000 ops/sec',
    statusPill: 'Operational 🟢',
    isEmployee: false,
    hash: '0x3E1B...884F',
    throughput: '0.000ms latency',
  },
  {
    id: 'mod-biometrics',
    code: 'SYS-BIO',
    name: 'Biometric Attendance Gateway',
    initials: 'BIO',
    designation: 'ZK-Teco Hardware Cloud Gateway',
    department: 'Data Ingestion',
    standardVar: 'attendanceGateway',
    category: 'Data Ingestion',
    angle: (Math.PI * 2 * 2) / 8,
    radius: 4.7,
    height: 0.7,
    description: 'Aggregates punch logs from cloud biometric devices and automatically evaluates unpaid Loss of Pay (LOP) withholding rules.',
    formula: 'lossOfPay = max(0, expectedWorkDays - verifiedBiometricPunches)',
    color: '#38bdf8',
    salaryNet: '21,480 Punches',
    salaryGross: 'Automated LOP',
    attendanceRate: 'Sync: 100%',
    statusPill: 'Connected ⚡',
    isEmployee: false,
    hash: '0x99A4...14EE',
    throughput: 'ZK-Cloud Gateway',
  },
  {
    id: 'mod-workflow',
    code: 'SYS-AUTH',
    name: '4-Stage Cryptographic Approvals',
    initials: 'APR',
    designation: 'Dual-Authorization Workflow Gate',
    department: 'Governance',
    standardVar: 'approvalGate',
    category: 'Governance',
    angle: (Math.PI * 2 * 3) / 8,
    radius: 5.0,
    height: -0.4,
    description: 'Enforces four-eye fiduciary governance requiring lead, finance, audit, and director verification before disbursal unlock.',
    formula: 'signoff(Stage_1) -> signoff(Stage_2) -> signoff(Stage_3) -> unlock(Disbursement)',
    color: '#f43f5e',
    salaryNet: '4-Eye Control',
    salaryGross: 'Tamper Resistant',
    attendanceRate: 'Audit Ready',
    statusPill: 'Locked & Verified 🛡️',
    isEmployee: false,
    hash: '0xC420...66F2',
    throughput: '4-Stage Gate',
  },
  {
    id: 'mod-anomalies',
    code: 'SYS-AI',
    name: 'Longitudinal Anomaly Detector',
    initials: 'AI',
    designation: 'Statistical Drift & Spike Scanner',
    department: 'Intelligence',
    standardVar: 'anomalyScanner',
    category: 'Intelligence',
    angle: (Math.PI * 2 * 4) / 8,
    radius: 4.6,
    height: 0.5,
    description: 'Scans compensation histories using statistical bounds to flag unindexed raises, duplicate bonuses, or negative net pay alerts.',
    formula: 'anomalyScore = abs(currentPayout - historicalMean) / stdDev',
    color: '#a855f7',
    salaryNet: 'Real-time Alerts',
    salaryGross: 'Zero Oversights',
    attendanceRate: 'Continuous Scan',
    statusPill: 'Scanning 🟢',
    isEmployee: false,
    hash: '0x81FA...D401',
    throughput: '3σ Outlier Bound',
  },
  {
    id: 'mod-statutory',
    code: 'SYS-STAT',
    name: 'Statutory Compliance Engine',
    initials: 'EPF',
    designation: 'EPFO & Tax Return Formatter',
    department: 'Compliance',
    standardVar: 'statutoryEngine',
    category: 'Compliance',
    angle: (Math.PI * 2 * 5) / 8,
    radius: 5.1,
    height: -0.3,
    description: 'Auto-generates EPFO Electronic Challan Returns (ECR) with UAN verification and quarterly Form 24Q income tax audit files.',
    formula: 'providentFund = min(basicSalary, 15000) * 0.12',
    color: '#f59e0b',
    salaryNet: 'EPFO ECR Ready',
    salaryGross: 'Form 24Q Validated',
    attendanceRate: 'State PT Slabs',
    statusPill: 'Audited 🛡️',
    isEmployee: false,
    hash: '0x55B0...334A',
    throughput: '1,428 UAN Verified',
  },
  {
    id: 'mod-escrow',
    code: 'SYS-CMS',
    name: 'Corporate Escrow Disburser',
    initials: 'CMS',
    designation: 'Institutional Banking Settlement',
    department: 'Settlement',
    standardVar: 'escrowGateway',
    category: 'Settlement',
    angle: (Math.PI * 2 * 6) / 8,
    radius: 4.8,
    height: 0.4,
    description: 'Connects directly to corporate escrow CMS accounts, generating 256-bit encrypted direct-deposit payment batches.',
    formula: 'directDeposit(escrowBalance >= netDisbursement)',
    color: '#ec4899',
    salaryNet: '256-bit Encrypted',
    salaryGross: 'CMS Connected',
    attendanceRate: 'Institutional Gate',
    statusPill: 'Settlement Ready 💳',
    isEmployee: false,
    hash: '0x29DF...BB80',
    throughput: '₹12.4 Cr Escrow',
  },
  {
    id: 'mod-audit',
    code: 'SYS-AUD',
    name: 'Autonomous Zero-Drift Ledger',
    initials: 'AUD',
    designation: 'Immutable Double-Entry Verifier',
    department: 'Governance',
    standardVar: 'auditLedger',
    category: 'Governance',
    angle: (Math.PI * 2 * 7) / 8,
    radius: 4.9,
    height: -0.5,
    description: 'Continuously verifies that all debit and credit entries balance to 0.00 cents with cryptographic cycle hashing.',
    formula: 'assert(sum(debits) == sum(credits) && drift == 0.00)',
    color: '#6366f1',
    salaryNet: '0.00% Drift',
    salaryGross: '₹0.00 Variance',
    attendanceRate: 'Immutable Log',
    statusPill: 'Zero Drift ⚡',
    isEmployee: false,
    hash: '0x00FF...0000',
    throughput: '256-Bit SHA Hashed',
  },
];
